# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


### JDBC URL 부분에 꼭 jdbc:h2:mem:testdb 넣어줘야함
//POST http://localhost:8080/request/posts
POST https://cafecostes.com/request/posts
Content-Type: application/json

{
    "name_box" : "asd",
    "email_box":
    "userLoginPassword": "테스트 본문",
    "userName": "테스터",
    "userEmail": "테스터",
    "userPhoneNumber": "테스터",
    "coupon" : 0


//    "orderMesage": "asd",
//    "msg": "hello",
//    "americano": "good",
//    "customList" : {
//        "id" : 1,
//        "customeName" : "shot",
//        "customCount" : 3
//    }

}
###